## Aufgabe 1: Schlüssel eines Dictionaries ausgeben

Ergänze den Code, um alle **Schlüssel** in `früchte` auszugeben.

In [ ]:
fruechte = {"Apfel": 3, "Banane": 5, "Kirsche": 8}
for ____ in fruechte:
    print(____)

## Aufgabe 2: Werte eines Dictionaries ausgeben

Ergänze den Code, um alle **Werte** in `früchte` auszugeben.

In [ ]:
fruechte = {"Apfel": 3, "Banane": 5, "Kirsche": 8}
for ____ in fruechte.values():
    print(____)

## Aufgabe 3: Schlüssel-Wert-Paare ausgeben

Ergänze den Code, um alle **Schlüssel-Wert-Paare** in `autos` auszugeben.

In [ ]:
autos = {"BMW": "X5", "Audi": "A6", "Mercedes": "C-Klasse"}
for ____ in autos.items():
    print(____, ":", ____)

## Aufgabe 4: Produkte und ihre Preise ausgeben

Ergänze den Code, um **jedes Produkt mit seinem Preis** aus `produkte` auszugeben.

In [ ]:
produkte = {"Laptop": 1200, "Handy": 800, "Tablet": 500}
for ____ in produkte.items():
    print(____)

## Aufgabe 5: Summe aller Preise berechnen

Ergänze den Code, um die **Summe aller Preise** in `produkte` zu berechnen.

In [ ]:
produkte = {"Laptop": 1200, "Handy": 800, "Tablet": 500}
summe = 0
for preis in produkte.values():
    summe += preis
print(summe)

## Aufgabe 6: Produkte mit Preis über 700 ausgeben

Ergänze den Code, um nur Produkte mit einem Preis **über 700** auszugeben.

In [ ]:
produkte = {"Laptop": 1200, "Handy": 800, "Tablet": 500}
for ____ in produkte.items():
    if ____:
        print(____)

## Aufgabe 7: Personen unter 30 ausgeben

Ergänze den Code, um nur Personen mit einem Alter **unter 30** auszugeben.

In [ ]:
personen = {"Anna": 25, "Ben": 30, "Clara": 22}
for ____ in personen.items():
    if ____:
        print(____)

## Aufgabe 8: Autos, die mit B beginnen

Ergänze den Code, um alle Autos auszugeben, die mit `'B'` beginnen.

In [ ]:
autos = {"BMW": "X5", "Audi": "A6", "Bentley": "Continental"}
for ____ in autos.keys():
    if ____:
        print(____)

## Aufgabe 9: Größte Städte ausgeben

Ergänze den Code, um nur die **größten Städte** aus `staedte` auszugeben (Einwohner > 1.000.000).

In [ ]:
staedte = {"Berlin": 3600000, "Hamburg": 1800000, "Köln": 1100000, "Leipzig": 600000}
for ____ in staedte.items():
    if ____:
        print(____)

## Aufgabe 10: Werte durch 2 teilbar

Ergänze den Code, um nur Werte auszugeben, die **durch 2 teilbar sind**.

In [ ]:
zahlen = {"a": 3, "b": 8, "c": 12, "d": 7}
for ____ in zahlen.items():
    if ____:
        print(____)

## Aufgabe 11: Liste aller Schlüssel erstellen

Ergänze den Code, um eine Liste mit allen **Schlüsseln** aus `personen` zu erstellen.

In [ ]:
personen = {"Anna": 25, "Ben": 30, "Clara": 22}
namen = []
for ____ in personen.keys():
    namen.append(____)
print(namen)

## Aufgabe 12: Liste aller Werte erstellen

Ergänze den Code, um eine Liste mit allen **Werten** aus `personen` zu erstellen.

In [ ]:
personen = {"Anna": 25, "Ben": 30, "Clara": 22}
alter = []
for ____ in personen.values():
    alter.append(____)
print(alter)

## Aufgabe 13: Personen über 25 speichern

Ergänze den Code, um eine Liste mit **Namen von Personen über 25** zu erstellen.

In [ ]:
personen = {"Anna": 25, "Ben": 30, "Clara": 22}
ueber_25 = []
for ____ in personen.items():
    if ____:
        ueber_25.append(____)
print(ueber_25)

## Aufgabe 14: Produkte im Preisbereich 500-1000

Ergänze den Code, um nur Produkte auszugeben, die **zwischen 500 und 1000** kosten.

In [ ]:
produkte = {"Laptop": 1200, "Handy": 800, "Tablet": 500}
for ____ in produkte.items():
    if ____:
        print(____)

## Aufgabe 15: Teuerstes Produkt finden

Ergänze den Code, um das teuerste Produkt aus `produkte` zu finden.

In [ ]:
produkte = {"Laptop": 1200, "Handy": 800, "Tablet": 500}
max_produkt = ""
max_preis = 0
for ____ in produkte.items():
    if ____:
        max_produkt = ____
        max_preis = ____
print(max_produkt, max_preis)

## Aufgabe 16: Personen über 30 oder unter 20

Ergänze den Code, um alle Personen auszugeben, die entweder **über 30 oder unter 20** sind.

In [ ]:
personen = {"Anna": 25, "Ben": 35, "Clara": 18, "David": 40}
for ____ in personen.items():
    if ____:
        print(____)

## Aufgabe 17: Erste Person über 30 finden

Ergänze den Code, um die **erste Person über 30** zu finden und dann die Schleife zu beenden.

In [ ]:
personen = {"Anna": 25, "Ben": 35, "Clara": 18, "David": 40}
for ____ in personen.items():
    if ____:
        print(____)
        break

## Aufgabe 18: Zahl überspringen

Ergänze den Code, um nur ungerade Werte aus `zahlen` auszugeben, aber `7` zu überspringen.

In [ ]:
zahlen = {"a": 3, "b": 7, "c": 9, "d": 11}
for ____ in zahlen.items():
    if ____:
        continue
    print(____)

## Aufgabe 19: Günstigstes Produkt finden

Ergänze den Code, um das **Produkt mit dem niedrigsten Preis** in `produkte` zu finden.

In [ ]:
produkte = {"Laptop": 1200, "Handy": 800, "Tablet": 500}
min_produkt = ""
min_preis = float("inf")
for ____ in produkte.items():
    if ____:
        min_produkt = ____
        min_preis = ____
print(min_produkt, min_preis)

## Aufgabe 20: Durchschnittsbewertung berechnen

Ergänze den Code, um die **Durchschnittsbewertung eines Films** aus `bewertungen` zu berechnen.

In [ ]:
bewertungen = {"Film A": [4, 5, 3, 5], "Film B": [2, 3, 3, 4], "Film C": [5, 5, 4, 5]}
durchschnittswerte = {}
for film, bewertungsliste in ____.items():
    durchschnittswerte[film] = sum(____) / len(____)
print(durchschnittswerte)