### Aufgabe 1: Eine Liste erstellen und auslesen
Erstelle eine Liste mit den Zahlen 1 bis 5. Gib die Liste aus.

# Deine Vermutung: ___

In [ ]:
zahlen = [1, 2, 3, 4, 5]
print(zahlen)

[1, 2, 3, 4, 5]

### Aufgabe 2: Wert zur Liste hinzufügen
Füge der Liste die Zahl 6 hinzu und gib sie erneut aus.

# Deine Vermutung: ___

In [ ]:
zahlen = [1, 2, 3, 4, 5]
zahlen.append(6)
print(zahlen)

[1, 2, 3, 4, 5, 6]

### Aufgabe 3: Wert aus Liste entfernen
Entferne die Zahl 3 aus der Liste.

# Deine Vermutung: ___

In [ ]:
zahlen = [1, 2, 3, 4, 5]
zahlen.remove(3)
print(zahlen)

[1, 2, 4, 5]

### Aufgabe 4: Überprüfen, ob ein Wert in der Liste ist
Überprüfe, ob die Zahl 4 in der Liste enthalten ist.

# Deine Vermutung: ___

In [ ]:
zahlen = [1, 2, 3, 4, 5]
print(4 in zahlen)

True

### Aufgabe 5: Ein Dictionary erstellen und auslesen
Erstelle ein Dictionary mit den Schlüsseln 'Name' und 'Alter'.

# Deine Vermutung: ___

In [ ]:
person = {'Name': 'Anna', 'Alter': 25}
print(person)

{'Name': 'Anna', 'Alter': 25}

### Aufgabe 6: Neuen Eintrag ins Dictionary hinzufügen
Füge die Information 'Stadt': 'Berlin' zum Dictionary hinzu.

# Deine Vermutung: ___

In [ ]:
person = {'Name': 'Anna', 'Alter': 25}
person['Stadt'] = 'Berlin'
print(person)

person['Tier'] = {'Hund': "Bello", 'Katze': 'Miau'}
print(person)

# code
# code
# code

person['Tier']['Maus'] = 'Pfieps'
print(person)

# Maus vorhanden?

print('Maus' in person['Tier'])

{'Name': 'Anna', 'Alter': 25, 'Stadt': 'Berlin'}
{'Name': 'Anna', 'Alter': 25, 'Stadt': 'Berlin', 'Tier': {'Hund': 'Bello', 'Katze': 'Miau'}}
{'Name': 'Anna', 'Alter': 25, 'Stadt': 'Berlin', 'Tier': {'Hund': 'Bello', 'Katze': 'Miau', 'Maus': 'Pfieps'}}
True

### Aufgabe 7: Wert aus dem Dictionary löschen
Entferne den Schlüssel 'Alter' aus dem Dictionary.

# Deine Vermutung: ___

In [ ]:
person = {'Name': 'Anna', 'Alter': 25, 'Stadt': 'Berlin'}
del person['Alter']
print(person)

{'Name': 'Anna', 'Stadt': 'Berlin'}

### Aufgabe 8: Existenz eines Schlüssels prüfen
Überprüfe, ob der Schlüssel 'Name' im Dictionary existiert.

# Deine Vermutung: ___

In [ ]:
person = {'Name': 'Anna', 'Stadt': 'Berlin'}
print('Name' in person)

True

### Aufgabe 9: Liste von Dictionaries
Erstelle eine Liste mit zwei Dictionaries – jeweils mit 'Name' und 'Alter'.

# Deine Vermutung: ___

In [ ]:
personen = [
    {'Name': 'Anna', 'Alter': 25},
    {'Name': 'Ben', 'Alter': 30}
]
print(personen[0])

{'Name': 'Anna', 'Alter': 25}

### Aufgabe 10: Auf verschachtelte Werte zugreifen
Gib das Alter der zweiten Person in der Liste aus.

# Deine Vermutung: ___

In [ ]:
personen = [
    {'Name': 'Anna', 'Alter': 25},
    {'Name': 'Ben', 'Alter': 30}
]
print(personen[1]['Alter'])

30

In [ ]:
# Finale:
deine_hotels = [
    {
        "Hotelname": "Hülton",
        "Stadt": "London",
        "Preis": 19,
        "Services": ["Wäsche", "Frühstück"],

    },
    {
        "Hotelname": "Morriot",
        "Stadt": "London",
        "Preis": 27,
        "Services": ["Wecker", "Frühstück"]
    },
    {
        "Hotelname": "Steves Garage",
        "Stadt": "London",
        "Preis": 5,
        "Services": ["Wäsche", "Frühstück"]
    }
]


# Aufgabe 1: Gib den Namen des ersten Hotels mit print() aus.

print(deine_hotels[0]["Hotelname"])

# Aufgabe 2: Überschreibe den Preis des zweiten Hotels mit dem Wert 30.

second_hotel = deine_hotels[1]
second_hotel["Preis"] = 30

print(second_hotel["Preis"])

# Aufgabe 3: Füge beim dritten Hotel den Service "WLAN" mit append() hinzu.

deine_hotels[2]["Services"].append("WLAN")
print(deine_hotels[2]["Services"])

# Aufgabe 4: Prüfe mit "in", ob "Wäsche" beim ersten Hotel ein Service ist. Gib True oder False aus.

if "Wäsche" in deine_hotels[0]["Services"]:
  print("Wäscheservice vorhanden!")

# Aufgabe 5: Entferne beim zweiten Hotel den Service "Wecker" mit remove().

deine_hotels[1]["Services"].remove("Wecker")
print(deine_hotels[1]["Services"])

# second_hotel = deine_hotels[1]
# services = second_hotel["Services"]
# services.remove("Wecker")
# print(services)

Hülton
30
['Wäsche', 'Frühstück', 'WLAN']
Wäscheservice vorhanden!
['Frühstück']

In [ ]:
deine_hotels = [
    {
        "Hotelname": "Hülton",
        "Stadt": "London",
        "Preis": 19,
        "Services": ["Wäsche", "Frühstück"],

    },
    {
        "Hotelname": "Morriot",
        "Stadt": "London",
        "Preis": 27,
        "Services": ["Wecker", "Frühstück"]
    },
    {
        "Hotelname": "Steves Garage",
        "Stadt": "London",
        "Preis": 5,
        "Services": ["Wäsche", "Frühstück"]
    }
]

deine_hotels[0]["Attraktionen"] = "Achterbahn"    # zu einem dict hinzufügen
deine_hotels[0]["Services"].append("Mittagessen") # zu einer lsite hinzufügen

print(deine_hotels)

[{'Hotelname': 'Hülton', 'Stadt': 'London', 'Preis': 19, 'Services': ['Wäsche', 'Frühstück', 'Mittagessen'], 'Attraktionen': 'Achterbahn'}, {'Hotelname': 'Morriot', 'Stadt': 'London', 'Preis': 27, 'Services': ['Wecker', 'Frühstück']}, {'Hotelname': 'Steves Garage', 'Stadt': 'London', 'Preis': 5, 'Services': ['Wäsche', 'Frühstück']}]

In [ ]:

# zuweisen von list und dict


a = 5
b = 2


c = a # c = 5 bei primitiven datentypen wird die varible immer mit einer kopie der anderen zugewiesen
a = 4

c = a # c = 4

d = a + c

print(d)



my_list_a = ["hallo", "tschüss" ]

my_list_b = my_list_a # bei listen und dictionaries wird eine referenz der neuen variable zugewiesen

my_list_b.append("hurraaaaay")
my_list_a.append("Yolo")

print(my_list_a)
print(my_list_b)

# keys()
# values()
# items()

8
['hallo', 'tschüss', 'hurraaaaay', 'Yolo']
['hallo', 'tschüss', 'hurraaaaay', 'Yolo']

In [ ]:
my_list_a = ["hallo", "tschüss" ]
my_list_b = ["Haus", "Maus"]

my_list_b = my_list_a.copy() # mit der copy() methode wird der neuen variablen eine vollständige Kopie zugewiesen

my_list_a.append("Yolo")
my_list_b.append("hurraaaaay")

print(my_list_a)
print(my_list_b)

# keys()
# values()
# items()

['hallo', 'tschüss', 'Yolo']
['hallo', 'tschüss', 'hurraaaaay']

In [ ]:


my_dict_a = {"Name": "Anna", "Alter": 30}

my_dict_b = my_dict_a.copy()

my_dict_b["Haustier"] = {"Hund": "Bella"}

print(my_dict_a)
print(my_dict_b)

{'Name': 'Anna', 'Alter': 30}
{'Name': 'Anna', 'Alter': 30, 'Haustier': {'Hund': 'Bella'}}

In [ ]:
my_dict_a = {"Name": "Anna", "Alter": 30, "Haustier": "Hund"}

print(my_dict_a.keys())

my_keys = list(my_dict_a.keys())
print(my_keys)

TypeError: 'list' object is not callable