## Aufgabe 1: Liste erstellen

Ergänze den Code, um eine **Liste** mit den Zahlen `1, 2, 3, 4, 5` zu erstellen.

In [ ]:
zahlen = ____
print(zahlen)  # Erwartete Ausgabe: [1, 2, 3, 4, 5]

## Aufgabe 2: Dictionary erstellen

Ergänze den Code, um ein **Dictionary** mit Namen als Schlüssel und Alter als Werte zu erstellen.

In [ ]:
personen = ____
print(personen)  # Erwartete Ausgabe: {'Anna': 25, 'Ben': 30, 'Clara': 22}

## Aufgabe 3: Drittes Element aus Liste abrufen

Ergänze den Code, um das **dritte Element** aus der Liste `früchte` zu erhalten.

In [ ]:
fruechte = ["Apfel", "Banane", "Kirsche"]
drittes_element = ____
print(drittes_element)

## Aufgabe 4: Wert aus Dictionary abrufen

Ergänze den Code, um das **Alter von Ben** aus dem Dictionary `personen` abzurufen.

In [ ]:
personen = {"Anna": 25, "Ben": 30, "Clara": 22}
alter_ben = ____
print(alter_ben)

## Aufgabe 5: Element zu Liste hinzufügen

Ergänze den Code, um `'Mango'` am Ende der Liste `früchte` hinzuzufügen.

In [ ]:
fruechte = ["Apfel", "Banane", "Kirsche"]
____
print(früchte)

## Aufgabe 6: Schlüssel-Wert zu Dictionary hinzufügen

Ergänze den Code, um `'David': 27` zu `personen` hinzuzufügen.

In [ ]:
personen = {"Anna": 25, "Ben": 30, "Clara": 22}
____
print(personen)

## Aufgabe 7: Element an den Anfang einer Liste einfügen

Ergänze den Code, um `'Birne'` an den **Anfang** der Liste `früchte` einzufügen.

In [ ]:
fruechte = ["Apfel", "Banane", "Kirsche"]
____
print(früchte)

## Aufgabe 8: Neues Auto zum Dictionary hinzufügen

Ergänze den Code, um `'Tesla': 'Model 3'` zum Dictionary `autos` hinzuzufügen.

In [ ]:
autos = {"BMW": "X5", "Audi": "A6"}
____
print(autos)

## Aufgabe 9: Element aus Liste entfernen

Ergänze den Code, um `'Banane'` aus der Liste `früchte` zu entfernen.

In [ ]:
fruechte = ["Apfel", "Banane", "Kirsche"]
____
print(früchte)

## Aufgabe 10: Schlüssel aus Dictionary entfernen

Ergänze den Code, um `'Clara'` aus `personen` zu entfernen.

In [ ]:
personen = {"Anna": 25, "Ben": 30, "Clara": 22}
____
print(personen)

## Aufgabe 11: Letztes Element aus Liste entfernen

Ergänze den Code, um das letzte Element aus der Liste `zahlen` zu entfernen.

In [ ]:
zahlen = [10, 20, 30, 40, 50]
____
print(zahlen)

## Aufgabe 12: Schlüssel aus Dictionary entfernen

Ergänze den Code, um `'Audi'` aus `autos` zu entfernen.

In [ ]:
autos = {"BMW": "X5", "Audi": "A6", "Tesla": "Model 3"}
____
print(autos)

## Aufgabe 13: Ersten Buchstaben eines Listenelements abrufen

Ergänze den Code, um den **ersten Buchstaben** des ersten Elements in `früchte` auszugeben.

In [ ]:
fruechte = ["Apfel", "Banane", "Kirsche"]
erster_buchstabe = ____
print(erster_buchstabe)

## Aufgabe 14: Wert in einem Dictionary ändern

Ergänze den Code, um das Alter von `'Ben'` im Dictionary `personen` auf `35` zu ändern.

In [ ]:
personen = {"Anna": 25, "Ben": 30, "Clara": 22}
____
print(personen)

## Aufgabe 15: Liste mit `for`-Schleife ausgeben

Ergänze den Code, um alle Elemente in der Liste `zahlen` auszugeben.

In [ ]:
zahlen = [1, 2, 3, 4, 5]
for ____ in zahlen:
    print(____)

## Aufgabe 16: Schlüssel eines Dictionaries mit `for`-Schleife ausgeben

Ergänze den Code, um alle Schlüssel in `autos` auszugeben.

In [ ]:
autos = {"BMW": "X5", "Audi": "A6", "Tesla": "Model 3"}
for ____ in autos:
    print(____)

## Aufgabe 17: Schlüssel-Wert-Paare eines Dictionaries ausgeben

Ergänze den Code, um alle Schlüssel-Wert-Paare aus `personen` auszugeben.

In [ ]:
personen = {"Anna": 25, "Ben": 30, "Clara": 22}
for ____ in personen.items():
    print(____)

## Aufgabe 18: Nur gerade Zahlen in einer Liste ausgeben

Ergänze den Code, um nur die geraden Zahlen in `zahlen` auszugeben.

In [ ]:
zahlen = [1, 2, 3, 4, 5, 6]
for zahl in ____:
    if ____:
        print(zahl)

## Aufgabe 19: Personen über 25 aus einem Dictionary filtern

Ergänze den Code, um nur Personen mit einem Alter über `25` auszugeben.

In [ ]:
personen = {"Anna": 25, "Ben": 30, "Clara": 22}
for name, alter in ____:
    if ____:
        print(name, alter)

## Aufgabe 20: Element an spezifischer Position in einer Liste einfügen

Ergänze den Code, um `'Python'` am **zweiten Platz** in der Liste `sprachen` einzufügen.

In [ ]:
sprachen = ["C++", "JavaScript"]
____
print(sprachen)